[package]
name = "rustica-conway"
version = "0.1.0"
edition = "2021"
description = "Conway's Game of Life implementation for the Rustica engine"

[dependencies]
rustica_foundation = { path = "../../Foundation" }
rustica-ecs = { path = "../../crates/rustica-ecs" }
