[workspace]
members = [
    "crates/rustica_build", 
    "crates/rustica_conway",
    "crates/rustica_foundation",
    "crates/rustica_geometry",
    "crates/rustica_graphics",
    "crates/rustica_render",
    "crates/rustica_shaders",
    "crates/rustica_window",
    "prototypes/001_basic_window",
    "prototypes/002_basic_wgpu",
    "prototypes/003_basic_triangle",  
]

disabled = [
    "prototypes/004_animated_triangle", 
    "prototypes/005_custom_shader",     
    "prototypes/006_basic_mesh",        
    "prototypes/007_uv_sphere",         
    "prototypes/008_teapot",            
    "prototypes/009_ecs_conway",        
    "prototypes/010_ecs_conway_graphics",
    "examples/001_integration",         
]
resolver = "2"
