[workspace]
members = [
    "Foundation",   
    "crates/rustica_build", 
    "crates/rustica_conway",
    "crates/rustica_foundation",
    "crates/rustica_geometry",
    "crates/rustica_graphics",
    "crates/rustica_render",
    "crates/rustica_shaders",
    "crates/rustica_window",
    "Prototypes/001-BasicWindow",
    "Prototypes/002-BasicWGPU",
    "Prototypes/003-BasicTriangle",
]

disabled = [
    "Prototypes/004-AnimatedTriangle",
    "Prototypes/005-CustomShader",
    "Prototypes/006-BasicMesh",
    "Prototypes/007-UVSphere",
    "Prototypes/008-Teapot",
    "Prototypes/009-ECS-Conway",
    "Prototypes/010-ECS-Conway-Graphics",
    "Examples/001-Integration",
]
resolver = "2"
