[workspace]
members = [
    "Foundation",   
    "crates/standard-shader", 
    "crates/window",
    "crates/render",
    "crates/render-derive",
    "crates/standard-geometry", # Added standard-geometry crate
    "crates/rustica-ecs",
    "Prototypes/001-BasicWindow",
    "Prototypes/002-BasicWGPU",
    "Prototypes/003-BasicTriangle",
    "Prototypes/004-AnimatedTriangle",
    "Prototypes/005-CustomShader",
    "Prototypes/006-BasicMesh",
    "Prototypes/007-UVSphere",
    "Prototypes/008-Teapot",
    # "Prototypes/009-ECS-Conway",
    # "Prototypes/010-ECS-Conway-Graphics",
    "Examples/001-Integration",
]

resolver = "2"
