[package]
name = "rustica_foundation"
version = "0.1.0"
edition = "2024"
description = "Foundation library for Rustica engine"

[dependencies]
cgmath = "0.18"
bytemuck = { version = "1.14", features = ["derive"] }
wgpu = "24.0.3"
