[package]
name = "rustica_ecs_prototype"
version = "0.1.0"
edition = "2021"

[dependencies]
rustica_foundation = { path = "../../crates/rustica_foundation" }
rustica_ecs = { path = "../../crates/rustica_ecs" }
