[package]
name = "rustica_ecs"
version = "0.1.0"
edition = "2021"
description = "Entity Component System implementation for the Rustica engine"

[dependencies]
rustica_foundation = { workspace = true }
