//! Standard shader implementation for the Rustica engine
//!
//! This crate provides a reusable standard shader implementation that supports
//! common features like vertex attributes, instancing, lighting, and animations.

// Include the bindings generated by build.rs
// This brings structs like `standard_shader::VertexInput`, `standard_shader::InstanceInput`,
// `standard_shader::Uniforms`, and layout constants into scope.
// include!(concat!(env!("OUT_DIR"), "/standard_shader_bindings.rs"));

use rustica_foundation::geometry::{GeometryBuilder}; // Assuming GeometryBuilder is here



// --- Vertex Factory ---
/// Create a prelude module to simplify imports
pub mod prelude {
    pub use crate::{
        
    };
}
