[package]
name = "triangle_poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = { workspace = true }
wgpu = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
pollster = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }
glam = { workspace = true }
# Correct path relative to the workspace root (c:\Users\Adam\git\Rustica)
# Corrected dependency name to use hyphen
rustica-shader-bindings = { path = "../../crates/core/crates/shader-bindings" }
