[package]
name = "rustica_foundation"
version = "0.1.0"
edition = "2024"
description = "Foundation library for Rustica engine"

[dependencies]
glam = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }
wgpu = { workspace = true }
