[package]
name = "rustica_window"
version = "0.1.0"
edition = "2024"
description = "Window management crate for Rustica engine"

[dependencies]
rustica_foundation = { path = "../../Foundation" }
winit = "0.30.9"
raw-window-handle = "0.6.0"

[dev-dependencies]
# Add any test-specific dependencies here

[features]
# Feature for tests that require a display
test-display = []
