[package]
name = "rustica_standard_shader"
version = "0.1.0"
edition = "2021"
description = "Standard shader implementations for the Rustica engine"
license = "MIT"

[dependencies]
rustica_render = { workspace = true }
rustica_render_derive = { workspace = true }
rustica_foundation = { workspace = true }
rustica_graphics = { workspace = true }
glam = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }
wgpu = { workspace = true }