[package]
name = "rustica_render_derive"
version = "0.1.0"
edition = "2024"
description = "Derive macros for rustica_render"

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["full", "extra-traits"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
bytemuck = { workspace = true }

[dev-dependencies]
trybuild = { workspace = true }
wgpu = { workspace = true }
rustica_render = { path = "../rustica_render" }
rustica_foundation = { path = "../rustica_foundation" }
